## 用物件導向的方式，建立屬於自己的normal scaler（標準化），其中要包含fit及transform功能

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
import numpy as np

In [10]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [11]:
#產生一個物件(StandardScaler是一個類別)
scaler = StandardScaler()

In [12]:
#顯示fit後的結果
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
scaler.mean_

array([ 0.5,  0.5])

In [24]:
scaler.var_

array([ 0.25,  0.25])

In [14]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [15]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])

## 寫出自己的Standard Scaler，命名為MyNormalScaler，定義fit、transform和fit_transform

In [48]:
class MyNormalScaler:
    def __init__(self):
        #self:指向物件的一個參考
        self.data_mean_ = None
        self.data_var_ = None
        
    def fit(self,data):
        self.data_mean_ = np.mean(data, axis=0)
        self.data_var_ = np.var(data, axis=0)
        
    def transform(self,data):
        #改用np.sqrt
        new_data = (np.array(data)-self.data_mean_)/np.sqrt(self.data_var_)
        return new_data
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)    

In [49]:
#測試和驗證
np.mean(data,axis =0)

array([ 0.5,  0.5])

In [50]:
#測試和驗證
np.var(data, axis=0)

array([ 0.25,  0.25])

In [51]:
#測試和驗證(錯誤)
(np.array(data)-scaler.with_mean)/scaler.with_std

array([[-1., -1.],
       [-1., -1.],
       [ 0.,  0.],
       [ 0.,  0.]])

## 驗證自己寫的結果是否和套件結果一致

In [52]:
myscaler = MyNormalScaler()

In [53]:
data

[[0, 0], [0, 0], [1, 1], [1, 1]]

In [54]:
myscaler.fit(data)

In [55]:
myscaler.data_mean_

array([ 0.5,  0.5])

In [56]:
myscaler.data_var_

array([ 0.25,  0.25])

In [57]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [58]:
myscaler_new = MyNormalScaler()

In [59]:
myscaler_new.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])